# Generated by Django 4.2.16 on 2024-12-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu_core", "0004_alter_user_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
