# Generated by Django 4.2.16 on 2024-12-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu_core", "0007_rename_id_user_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="id",
        ),
    ]
