# Generated by Django 4.2.16 on 2024-12-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu_core", "0008_rename_user_id_user_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
