# Generated by Django 4.2.16 on 2024-12-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_core", "0011_alter_course_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="student",
        ),
        migrations.RemoveField(
            model_name="course",
            name="teacher",
        ),
        migrations.AddField(
            model_name="course",
            name="student",
            field=models.ManyToManyField(blank=True, null=True, to="edu_core.student"),
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ManyToManyField(blank=True, null=True, to="edu_core.teacher"),
        ),
    ]
