# Generated by Django 4.2.16 on 2024-12-12 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("edu_core", "0012_remove_course_student_remove_course_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="edu_core.course",
            ),
        ),
    ]
