# Generated by Django 4.2.16 on 2025-01-02 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("field_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submissions_count", models.IntegerField(default=0)),
                ("views_count", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(blank=True, max_length=100, null=True)),
                ("label_text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "label_vedio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formfields",
                        to="type_form.field",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formfields",
                        to="type_form.form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormFieldSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("multiple_selection", models.BooleanField(blank=True, null=True)),
                (
                    "multiple_selection_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unlimited", "Unlimited"),
                            ("exact number", "Exact Number"),
                            ("range", "Range"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("choices", models.JSONField(blank=True, null=True)),
                (
                    "exact_number_of_selections",
                    models.IntegerField(blank=True, null=True),
                ),
                ("max_number", models.IntegerField(blank=True, null=True)),
                ("min_number", models.IntegerField(blank=True, null=True)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                ("min_length", models.IntegerField(blank=True, null=True)),
                ("other_option", models.BooleanField(blank=True, null=True)),
                ("vertical_alignment", models.BooleanField(blank=True, null=True)),
                ("alphabetical_order", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_private", models.BooleanField(default=False)),
                ("max_invites", models.IntegerField(default=10)),
                ("invites_sent", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="type_form.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                ("is_accepted", models.BooleanField(default=False)),
                ("expiry_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="type_form.user",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="type_form.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("in progress", "In Progress"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        choices=[("desktop", "Desktop"), ("mobile", "Mobile")],
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formresponses",
                        to="type_form.form",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formresponses",
                        to="type_form.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormFieldResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                (
                    "form_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fieldresponses",
                        to="type_form.formfield",
                    ),
                ),
                (
                    "form_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fieldresponses",
                        to="type_form.formresponse",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="formfield",
            name="settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formfields",
                to="type_form.formfieldsettings",
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formfields",
                to="type_form.user",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="fields",
            field=models.ManyToManyField(
                through="type_form.FormField", to="type_form.field"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="type_form.user",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="type_form.workspace",
            ),
        ),
    ]
