# Generated by Django 4.2.16 on 2024-12-23 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicForm",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubmittedFormData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitteddata",
                        to="type_form.dynamicform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DynamicFormField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("Text", "Text Field"),
                            ("Integer", "Interger Field"),
                            ("Float", "Float Field"),
                            ("Email", "Email Field"),
                            ("Decimal", "Decimal Field"),
                            ("Boolean", "Boolean Field"),
                            ("DateTime", "DataTime Field"),
                            ("UUID", "UUID Field"),
                            ("Binary", "Binary Field"),
                            ("Date", "Date Field"),
                            ("Time", "Time Field"),
                            ("JSON", "JSON Field"),
                            ("PhoneNumber", "Phone Number Field"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_required", models.BooleanField()),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="type_form.dynamicform",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dynamicform",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="type_form.user"
            ),
        ),
    ]
