# Generated by Django 4.2.16 on 2025-01-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("type_form", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formresponse",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
