# Generated by Django 4.2.16 on 2025-01-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "type_form",
            "0003_layout_tab_remove_form_fields_tabfield_layout_form_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tabfield",
            name="field",
        ),
        migrations.RemoveField(
            model_name="tabfield",
            name="settings",
        ),
        migrations.RemoveField(
            model_name="tabfield",
            name="tab",
        ),
        migrations.RemoveField(
            model_name="tabfield",
            name="user",
        ),
        migrations.DeleteModel(
            name="Tab",
        ),
        migrations.DeleteModel(
            name="TabField",
        ),
    ]
