# Generated by Django 4.2.16 on 2025-01-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("type_form", "0005_tab"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="name",
            new_name="form_name",
        ),
        migrations.RenameField(
            model_name="workspace",
            old_name="name",
            new_name="workspace_name",
        ),
    ]
