# Generated by Django 4.2.16 on 2025-01-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("type_form", "0006_rename_name_form_form_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="type_form.tab",
            ),
        ),
    ]
