# Generated by Django 4.2.16 on 2025-01-09 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("door_no", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("pincode", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=255)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("HOUSE", "HOUSE"),
                            ("APARTMENT", "APARTMENT"),
                            ("BUSINESS", "BUSINESS"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255, unique=True)),
                ("price", models.FloatField()),
                ("number_of_left_in_stock", models.IntegerField()),
                ("number_of_purchases_in_last_month", models.IntegerField()),
                ("views", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="amazon.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemProperty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_status", models.CharField(max_length=255)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateTimeField()),
                (
                    "Item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.item"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.address"
                    ),
                ),
                (
                    "itemproperties",
                    models.ManyToManyField(
                        related_name="orders", to="amazon.itemproperty"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_type", models.CharField(max_length=50)),
                ("card_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "card_holder_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("cvv", models.CharField(blank=True, max_length=10, null=True)),
                ("card_type", models.CharField(blank=True, max_length=50, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=50, null=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("password", models.CharField(blank=True, max_length=50, null=True)),
                ("upi_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("contact_number", models.CharField(max_length=10, unique=True)),
                (
                    "address",
                    models.ManyToManyField(
                        related_name="user_address", to="amazon.address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Whishlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "items",
                    models.ManyToManyField(related_name="whishlists", to="amazon.item"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("payment_status", models.CharField(max_length=50)),
                ("transaction_id", models.CharField(max_length=50, unique=True)),
                (
                    "gift_card_or_promo_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="amazon.order",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="amazon.paymentmethod",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="amazon.user"
            ),
        ),
        migrations.CreateModel(
            name="ItemsWhishlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemswhishlist",
                        to="amazon.item",
                    ),
                ),
                (
                    "itemproperties",
                    models.ManyToManyField(
                        related_name="itemswhishlist", to="amazon.itemproperty"
                    ),
                ),
                (
                    "whishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemswhishlist",
                        to="amazon.whishlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemsCart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemscart",
                        to="amazon.cart",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemscart",
                        to="amazon.item",
                    ),
                ),
                (
                    "itemproperties",
                    models.ManyToManyField(
                        related_name="itemscart", to="amazon.itemproperty"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemproperty",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="amazon.property"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="properties",
            field=models.ManyToManyField(related_name="items", to="amazon.property"),
        ),
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(related_name="carts", to="amazon.item"),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="amazon.user"
            ),
        ),
    ]
