# Generated by Django 4.2.16 on 2025-01-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="Item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="amazon.item",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="itemproperties",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="orders", to="amazon.itemproperty"
            ),
        ),
    ]
