# Generated by Django 4.2.16 on 2025-01-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0004_deliveryavailability_emi_exchangeproperty_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="properties",
            field=models.ManyToManyField(related_name="items", to="amazon.property"),
        ),
    ]
