# Generated by Django 4.2.16 on 2025-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0007_remove_cart_items_remove_whishlist_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="expiry_date",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
