# Generated by Django 4.2.16 on 2025-01-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0008_remove_user_address_alter_paymentmethod_expiry_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="Item",
            new_name="item",
        ),
    ]
