# Generated by Django 4.2.16 on 2025-01-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0011_refund"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="about_this_item",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="discount_in_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="discount_in_rupees",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_best_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="is_new_release",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="is_top_brand",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="packaging",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="payment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="service_replacement_in_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="ships_from",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="sold_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="amazon.deliveryservice",
            ),
        ),
    ]
