# Generated by Django 4.2.16 on 2025-01-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0012_deliveryservice_item_about_this_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemscart",
            name="itememi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itemscart",
                to="amazon.itememi",
            ),
        ),
        migrations.AddField(
            model_name="itemscart",
            name="itemoffers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="itemscart", to="amazon.itemoffer"
            ),
        ),
    ]
