# Generated by Django 4.2.16 on 2025-01-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0013_itemscart_itememi_itemscart_itemoffers"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="itememi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="amazon.itememi",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="itemexchangeproperties",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="orders",
                to="amazon.itemexchangeproperty",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="itemoffers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="orders", to="amazon.itemoffer"
            ),
        ),
    ]
