# Generated by Django 4.2.16 on 2025-01-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0014_order_itememi_order_itemexchangeproperties_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemscart",
            name="itememi",
        ),
        migrations.RemoveField(
            model_name="itemscart",
            name="itemoffers",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="order",
            name="item",
        ),
        migrations.RemoveField(
            model_name="order",
            name="itememi",
        ),
        migrations.RemoveField(
            model_name="order",
            name="itemexchangeproperties",
        ),
        migrations.RemoveField(
            model_name="order",
            name="itemoffers",
        ),
        migrations.RemoveField(
            model_name="order",
            name="itemproperties",
        ),
        migrations.RemoveField(
            model_name="order",
            name="itemwarranty",
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_in_cart", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.item"
                    ),
                ),
                (
                    "itememi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderitem",
                        to="amazon.itememi",
                    ),
                ),
                (
                    "itemexchangeproperties",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="orderitem",
                        to="amazon.itemexchangeproperty",
                    ),
                ),
                (
                    "itemoffers",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="orderitem",
                        to="amazon.itemoffer",
                    ),
                ),
                (
                    "itemproperties",
                    models.ManyToManyField(
                        related_name="orderitem", to="amazon.itemproperty"
                    ),
                ),
                (
                    "itemwarranty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderitem",
                        to="amazon.itemwarranty",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.order"
                    ),
                ),
            ],
        ),
    ]
