# Generated by Django 4.2.16 on 2025-01-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "amazon",
            "0015_remove_itemscart_itememi_remove_itemscart_itemoffers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_shipped",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refund",
            name="items",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="refunds", to="amazon.item"
            ),
        ),
    ]
